version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - certbot-data:/etc/letsencrypt
      - ./var/www/certbot:/var/www/certbot
    networks:
      - app-network
    depends_on:
      certbot:
        condition: service_completed_successfully

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-data:/etc/letsencrypt
      - ./var/www/certbot:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email aleexkomendantov@gmail.com --agree-tos --no-eff-email -d xn--80aaggeaa5ahcgrocjg4b2a.xn--j1aef.xn--p1ai
    healthcheck:
      test: ["CMD", "ls", "/etc/letsencrypt/live/xn--80aaggeaa5ahcgrocjg4b2a.xn--j1aef.xn--p1ai/fullchain.pem"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  certbot-data:
  